---
- name: 'Dell Core 01/02 SW'
  connection: network_cli
  gather_facts: false
  hosts: all

  vars_prompt:
  - name: Route
    private: no
    prompt: "Ingrese ruta"

  vars_files:
    - vars/dellos10.yaml

  tasks:
  - name: Get route {{ Route }} from Router Cores
    dellos10_command:
      commands: 
        - show ip route | grep {{ Route }}
    register: route_found 
 
  - name: Failed route {{ Route }}/24 in Router Cores not found
    fail: msg="{{ Route }} is not in the routing table"
    when : 
      - Route not in route_found.stdout[0]

  - name: Route {{ Route }}/24 in Router Cores was found
    debug: msg="{{ route_found.stdout}}"
    when : 
      - Route in route_found.stdout[0]
